server:
  port: 5000
security:
  basic:
    realm: KekMovie
spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=FILM_SERVICE
    username: sa
    password: 3korif8245ef
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true